# ______ _                       _                    _  #
# | ___ \ |                     | |                  | | #
# | |_/ / | __ _ _   _  ___ _ __| |     _____   _____| | #
# |  __/| |/ _` | | | |/ _ \ '__| |    / _ \ \ / / _ \ | #
# | |   | | (_| | |_| |  __/ |  | |___|  __/\ V /  __/ | #
# \_|   |_|\__,_|\__, |\___|_|  \_____/\___| \_/ \___|_| #
#                 __/ |                                  #
#                |___/                                   #

# 全局设置
options:
  # 插件更新提醒
  update: true
  # 启用bstats统计
  metrics: true
  # 启用调试模式
  debug: false
  # 数据存储相关
  database:
    # 存储方式 (JSON, CBOR)
    type: JSON
    uri: database.json
  # 玩家经验达标后自动升级
  auto-level-up: true
  # 玩家满级后不再获取经验
  exp-limit: false
  # 原版经验条与PlayerLevel同步
  exp-bar: true
  # 获得原版经验转换为PlayerExp的倍率 (类型为Double, PlayerExp为小数时四舍五入)
  # 当该数值为0.0时, 原版经验不会转化为PlayerExp
  # 当该数值为2.0时, 每获得1点原版经验, PlayerExp将对应增加2点
  exp-conversion-rate: 0.0
  # 特殊命令中空格的转义字符
  space-replace: "#"