# ______ _                       _                    _  #
# | ___ \ |                     | |                  | | #
# | |_/ / | __ _ _   _  ___ _ __| |     _____   _____| | #
# |  __/| |/ _` | | | |/ _ \ '__| |    / _ \ \ / / _ \ | #
# | |   | | (_| | |_| |  __/ |  | |___|  __/\ V /  __/ | #
# \_|   |_|\__,_|\__, |\___|_|  \_____/\___| \_/ \___|_| #
#                 __/ |                                  #
#                |___/                                   #

# 全局设置
options:
  # 插件更新提醒
  update: true
  # 启用bstats统计
  metrics: true
  # 启用调试模式
  debug: false
  # 数据存储相关
  database:
    # 存储方式 (LOCAL,SQL)
    use: LOCAL
    # 数据库设置
    sql:
      host: 127.0.0.1
      port: 3306
      user: root
      password: 123456
      database: PlayerLevel