#     _    _              _ _                   _  #
#    / \  | | ____ _ _ __(_) |    _____   _____| | #
#   / _ \ | |/ / _` | '__| | |   / _ \ \ / / _ \ | #
#  / ___ \|   < (_| | |  | | |__|  __/\ V /  __/ | #
# /_/   \_\_|\_\__,_|_|  |_|_____\___| \_/ \___|_| #

##################################
#       AkariLevel  Config       #
##################################

###########
# Options #
###########

# 全局设置
Options:
  # 配置文件版本
  Config-Version: 1
  # 检查版本更新
  Check-Update: true
  # 启用 bStats 统计
  Send-Metrics: true
  # 启用调试模式
  Debug: false

############
# Database #
############

# 数据存储设置
Database:
  # 存储方式 (JSON, CBOR, SQL)
  Method: JSON
  JSON:
    file: database.json
  CBOR:
    file: database.cbor
  SQL:
    host: localhost
    port: 3306
    user: root
    password: password
    database: minecraft
    table: akarilevel

###########
#  Level  #
###########

# 等级设置
Level:
  # 满足要求自动升级
  Auto-Levelup: true
  # 达到最大等级后不再获取经验
  Exp-Limit: true
  # 将原版经验条与 AkariLevel 同步
  Vanilla-Exp-Bar: true
  # 原版经验转换为 AkariExp 的倍率 (类型为Double)
  # AkariExp 改变量 = 四舍五入至整数 ( 原版经验改变量 * Exp-Rate )
  Vanilla-Exp-Rate: 0.0

##########
#  Hook  #
##########

# 挂钩设置
Hook:
  # MythicMobs 掉落拓展
  MythicMobs:
    # 是否启用
    Enable: true
    # 经验掉落名称
    # 继承自 2.X 的掉落物名称 PlayerExp
    # Drop-Name: "PlayerExp"
    Drop-Name: "AkariExp"
  # 属性插件经验加成拓展
  # 继承自 2.X 附属 AttributeLevel
  Attribute:
    # 是否启用
    Enable: true
    # 属性插件 (AttributePlus, SX-Attribute)
    Plugin: "AttributePlus"
    # 属性名称
    # 注意：SX-Attribute的属性名称是其英文名而非DiscernName (即默认应填写"ExpAddition"而非"经验增幅")
    Name: "经验加成"
    # 经验计算公式
    # 预设:
    # %exp% -> 获得的经验值数量
    # %attribute% -> 额外加成经验数量
    Formula: "%exp% * ( 1 + %attribute% / 100 )"
    # 所监听的 PlayerExpChange 来源
    Source:
      - "MYTHICMOBS_EXP_DROP"
  # PlaceholderAPI 变量拓展
  PlaceholderAPI:
    # 变量前缀
    # 继承自 2.X 的变量前缀 playerlevel
    # Identifier: "playerlevel"
    Identifier: "akarilevel"